/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TPSCanvasNotesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/canvas-extension.ts
var import_view = require("@codemirror/view");
var import_state2 = require("@codemirror/state");
var import_obsidian3 = require("obsidian");

// src/card-parser.ts
function parseCards(state) {
  var _a;
  const doc = state.doc;
  const cards = [];
  const lines = [];
  for (let i = 1; i <= doc.lines; i++) {
    lines.push(doc.line(i).text);
  }
  let contentStartLine = 0;
  if (((_a = lines[0]) == null ? void 0 : _a.trim()) === "---") {
    const frontmatterEnd = lines.findIndex((line, idx) => idx > 0 && line.trim() === "---");
    if (frontmatterEnd !== -1) {
      contentStartLine = frontmatterEnd + 1;
    }
  }
  const delimiterLines = [];
  for (let i = contentStartLine; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      delimiterLines.push(i);
    }
  }
  if (delimiterLines.length === 0) {
    const startLine = contentStartLine;
    const endLine = lines.length - 1;
    if (startLine <= endLine) {
      const startPos = doc.line(startLine + 1).from;
      const endPos = doc.line(endLine + 1).to;
      const cardText = doc.sliceString(startPos, endPos).trim();
      return [{
        startLine,
        endLine,
        startPos,
        endPos,
        isEmpty: cardText.length === 0
      }];
    }
    return [];
  }
  for (let i = 0; i < delimiterLines.length - 1; i++) {
    const startLine = delimiterLines[i];
    const endLine = delimiterLines[i + 1];
    const contentStartLine2 = startLine + 1;
    const contentEndLine = endLine - 1;
    if (contentStartLine2 <= contentEndLine) {
      const startPos = doc.line(contentStartLine2 + 1).from;
      const endPos = doc.line(contentEndLine + 1).to;
      const cardText = doc.sliceString(startPos, endPos).trim();
      cards.push({
        startLine: contentStartLine2,
        endLine: contentEndLine,
        startPos,
        endPos,
        isEmpty: cardText.length === 0
      });
    }
  }
  return cards;
}
function getDelimiterLines(state) {
  var _a;
  const doc = state.doc;
  const lines = [];
  const delimiterLines = [];
  let contentStartLine = 0;
  for (let i = 1; i <= doc.lines; i++) {
    lines.push(doc.line(i).text);
  }
  if (((_a = lines[0]) == null ? void 0 : _a.trim()) === "---") {
    const frontmatterEnd = lines.findIndex((line, idx) => idx > 0 && line.trim() === "---");
    if (frontmatterEnd !== -1) {
      contentStartLine = frontmatterEnd + 1;
    }
  }
  for (let i = contentStartLine; i < lines.length; i++) {
    if (lines[i].trim() === "---") {
      delimiterLines.push(i);
    }
  }
  return delimiterLines;
}

// src/insertion-zone-handler.ts
var import_obsidian = require("obsidian");
var InsertionZoneHandler = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Handle left-click: insert new empty card
   */
  handleClick(view, pos) {
    const line = view.state.doc.lineAt(pos);
    view.dispatch({
      changes: {
        from: line.from,
        insert: "---\n\n---\n"
      },
      selection: { anchor: line.from + 5 }
      // Position cursor inside new card
    });
  }
  /**
   * Handle right-click: show file picker to embed existing note
   */
  handleRightClick(view, pos, event) {
    event.preventDefault();
    new FileSuggestModal(this.app, (file) => {
      const line = view.state.doc.lineAt(pos);
      view.dispatch({
        changes: {
          from: line.from,
          insert: `---
![[${file.basename}]]
---
`
        }
      });
    }).open();
  }
};
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChooseItem) {
    super(app);
    this.onChooseCallback = onChooseItem;
    this.setPlaceholder("Select a file to embed as a card...");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChooseCallback(file);
  }
};

// src/card-extract-service.ts
var import_obsidian2 = require("obsidian");
var CardExtractService = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Extract a card to a new note and replace with embed
   */
  async extractCard(view, card, currentFile) {
    const content = view.state.doc.sliceString(card.startPos, card.endPos).trim();
    if (!content) {
      new import_obsidian2.Notice("Cannot extract empty card");
      return;
    }
    const firstLine = content.split("\n")[0];
    const filename = this.sanitizeFilename(this.extractTitle(firstLine));
    const newFilePath = this.getNewFilePath(filename);
    try {
      const newFile = await this.app.vault.create(newFilePath, content);
      const doc = view.state.doc;
      const startDelimiterLine = doc.line(card.startLine);
      const endDelimiterLine = doc.line(card.endLine + 2);
      view.dispatch({
        changes: {
          from: card.startPos,
          to: card.endPos,
          insert: `![[${newFile.basename}]]`
        }
      });
      new import_obsidian2.Notice(`Card extracted to "${newFile.basename}"`);
    } catch (error) {
      console.error("Failed to extract card:", error);
      new import_obsidian2.Notice("Failed to extract card: " + error.message);
    }
  }
  /**
   * Extract title from first line of content (strip markdown syntax)
   */
  extractTitle(firstLine) {
    let title = firstLine.replace(/^#+\s*/, "");
    title = title.replace(/[*_~`]/g, "");
    title = title.replace(/\[\[([^\]]+)\]\]/g, "$1");
    title = title.replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1");
    title = title.trim();
    if (title.length > 50) {
      title = title.substring(0, 50);
    }
    return title || `Untitled ${Date.now()}`;
  }
  /**
   * Sanitize filename (remove invalid characters)
   */
  sanitizeFilename(filename) {
    return filename.replace(/[\\/:*?"<>|]/g, "-");
  }
  /**
   * Get the path for a new file based on vault settings
   */
  getNewFilePath(filename) {
    var _a;
    const newFileLocation = this.app.vault.getConfig("newFileLocation");
    const newFileFolderPath = this.app.vault.getConfig("newFileFolderPath");
    let folderPath = "";
    if (newFileLocation === "folder") {
      folderPath = newFileFolderPath || "";
    } else if (newFileLocation === "current") {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        folderPath = ((_a = activeFile.parent) == null ? void 0 : _a.path) || "";
      }
    }
    const path = folderPath ? `${folderPath}/${filename}.md` : `${filename}.md`;
    return (0, import_obsidian2.normalizePath)(path);
  }
};

// src/read-only-filter.ts
var import_state = require("@codemirror/state");
function createReadOnlyFilter() {
  return import_state.EditorState.transactionFilter.of((tr) => {
    if (!tr.docChanged) {
      return tr;
    }
    const cards = parseCards(tr.startState);
    if (cards.length === 0) {
      return [];
    }
    let hasInvalidChange = false;
    tr.changes.iterChanges((fromA, toA, fromB, toB, inserted) => {
      const isInCard = cards.some((card) => {
        return fromA >= card.startPos && toA <= card.endPos;
      });
      if (!isInCard) {
        const insertedText = inserted.toString();
        if (!insertedText.includes("---")) {
          hasInvalidChange = true;
        }
      }
    });
    if (hasInvalidChange) {
      return [];
    }
    return tr;
  });
}

// src/canvas-extension.ts
var InsertionZoneWidget = class extends import_view.WidgetType {
  constructor(handler, pos) {
    super();
    this.handler = handler;
    this.pos = pos;
  }
  eq(other) {
    return other.pos === this.pos;
  }
  toDOM(view) {
    const zone = document.createElement("div");
    zone.className = "tps-card-insertion-zone";
    zone.setAttribute("data-pos", this.pos.toString());
    zone.addEventListener("click", (e) => {
      e.preventDefault();
      this.handler.handleClick(view, this.pos);
    });
    zone.addEventListener("contextmenu", (e) => {
      this.handler.handleRightClick(view, this.pos, e);
    });
    return zone;
  }
  ignoreEvent() {
    return false;
  }
};
var CardMenuWidget = class extends import_view.WidgetType {
  constructor(app, card, extractService) {
    super();
    this.app = app;
    this.card = card;
    this.extractService = extractService;
  }
  eq(other) {
    return other.card.startPos === this.card.startPos && other.card.endPos === this.card.endPos;
  }
  toDOM(view) {
    const container = document.createElement("div");
    container.className = "tps-card-menu-button";
    (0, import_obsidian3.setIcon)(container, "more-vertical");
    container.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const menu = new import_obsidian3.Menu();
      menu.addItem(
        (item) => item.setTitle("Extract to note").setIcon("file-plus").onClick(async () => {
          const file = this.app.workspace.getActiveFile();
          if (file) {
            await this.extractService.extractCard(view, this.card, file);
          }
        })
      );
      menu.addItem(
        (item) => item.setTitle("Delete card").setIcon("trash").onClick(() => {
          const doc = view.state.doc;
          const startDelimiterLine = doc.line(this.card.startLine);
          const endDelimiterLine = doc.line(this.card.endLine + 2);
          view.dispatch({
            changes: {
              from: startDelimiterLine.from - 4,
              // Include the --- above
              to: endDelimiterLine.to + 1
              // Include the --- below and newline
            }
          });
        })
      );
      menu.showAtMouseEvent(e);
    });
    return container;
  }
  ignoreEvent() {
    return true;
  }
};
var CanvasExtension = class {
  constructor(view, app) {
    this.draggedCard = null;
    this.app = app;
    this.insertionHandler = new InsertionZoneHandler(app);
    this.extractService = new CardExtractService(app);
    this.decorations = this.buildDecorations(view);
  }
  update(update) {
    if (update.docChanged || update.viewportChanged || update.selectionSet) {
      this.decorations = this.buildDecorations(update.view);
    }
  }
  buildDecorations(view) {
    const builder = new import_state2.RangeSetBuilder();
    const cards = parseCards(view.state);
    const delimiterLines = getDelimiterLines(view.state);
    const decorations = [];
    for (const lineNum of delimiterLines) {
      const line = view.state.doc.line(lineNum + 1);
      decorations.push({
        from: line.from,
        to: line.from,
        decoration: import_view.Decoration.line({ class: "tps-card-delimiter-hidden" })
      });
    }
    for (let i = 0; i < cards.length; i++) {
      const card = cards[i];
      for (let lineNum = card.startLine; lineNum <= card.endLine; lineNum++) {
        const line = view.state.doc.line(lineNum + 1);
        decorations.push({
          from: line.from,
          to: line.from,
          decoration: import_view.Decoration.line({
            class: card.isEmpty ? "tps-canvas-card-line tps-canvas-card-empty" : "tps-canvas-card-line"
          })
        });
      }
      const firstLine = view.state.doc.line(card.startLine + 1);
      decorations.push({
        from: firstLine.to,
        to: firstLine.to,
        decoration: import_view.Decoration.widget({
          widget: new CardMenuWidget(this.app, card, this.extractService),
          side: 1
        })
      });
      const lastLine = view.state.doc.line(card.endLine + 1);
      decorations.push({
        from: lastLine.to,
        to: lastLine.to,
        decoration: import_view.Decoration.widget({
          widget: new InsertionZoneWidget(this.insertionHandler, lastLine.to),
          side: 1
        })
      });
    }
    if (cards.length > 0) {
      const lastLine = view.state.doc.line(view.state.doc.lines);
      decorations.push({
        from: lastLine.to,
        to: lastLine.to,
        decoration: import_view.Decoration.widget({
          widget: new InsertionZoneWidget(this.insertionHandler, lastLine.to),
          side: 1
        })
      });
    }
    decorations.sort((a, b) => a.from - b.from);
    for (const { from, to, decoration } of decorations) {
      builder.add(from, to, decoration);
    }
    return builder.finish();
  }
  destroy() {
  }
};
function buildCanvasExtension(app, shouldActivate) {
  const viewPlugin = import_view.ViewPlugin.define(
    (view) => new CanvasExtension(view, app),
    {
      decorations: (v) => {
        if (shouldActivate && !shouldActivate()) {
          return import_view.Decoration.none;
        }
        return v.decorations;
      },
      eventHandlers: {
        dragstart: (e, view) => {
          if (shouldActivate && !shouldActivate()) {
            return false;
          }
          const target = e.target;
          if (!target.closest(".tps-canvas-card-line")) {
            return false;
          }
          const pos = view.posAtDOM(target);
          const cards = parseCards(view.state);
          const card = cards.find((c) => pos >= c.startPos && pos <= c.endPos);
          if (!card)
            return false;
          const content = view.state.doc.sliceString(card.startPos, card.endPos);
          if (e.dataTransfer) {
            e.dataTransfer.setData("text/plain", content);
            e.dataTransfer.setData(
              "application/tps-canvas-card",
              JSON.stringify({
                startPos: card.startPos,
                endPos: card.endPos,
                startLine: card.startLine,
                endLine: card.endLine
              })
            );
            e.dataTransfer.effectAllowed = "move";
          }
          target.classList.add("tps-card-dragging");
          return false;
        },
        dragover: (e, view) => {
          var _a;
          if (shouldActivate && !shouldActivate()) {
            return false;
          }
          if (!((_a = e.dataTransfer) == null ? void 0 : _a.types.includes("application/tps-canvas-card"))) {
            return false;
          }
          e.preventDefault();
          if (e.dataTransfer) {
            e.dataTransfer.dropEffect = "move";
          }
          return true;
        },
        drop: (e, view) => {
          var _a;
          if (shouldActivate && !shouldActivate()) {
            return false;
          }
          if (!((_a = e.dataTransfer) == null ? void 0 : _a.types.includes("application/tps-canvas-card"))) {
            return false;
          }
          e.preventDefault();
          const cardDataRaw = e.dataTransfer.getData("application/tps-canvas-card");
          if (!cardDataRaw)
            return true;
          let cardData;
          try {
            cardData = JSON.parse(cardDataRaw);
          } catch (e2) {
            return true;
          }
          const dropPos = view.posAtCoords({ x: e.clientX, y: e.clientY });
          if (dropPos === null)
            return true;
          const cards = parseCards(view.state);
          let insertBeforeCard = null;
          for (const card of cards) {
            if (dropPos < card.startPos) {
              insertBeforeCard = card;
              break;
            }
          }
          if (insertBeforeCard && insertBeforeCard.startPos === cardData.startPos) {
            return true;
          }
          const doc = view.state.doc;
          const sourceStartDelim = doc.line(cardData.startLine);
          const sourceEndDelim = doc.line(cardData.endLine + 2);
          const fullCardContent = doc.sliceString(
            sourceStartDelim.from - 4,
            sourceEndDelim.to
          );
          let insertPos;
          if (insertBeforeCard) {
            const targetDelim = doc.line(insertBeforeCard.startLine);
            insertPos = targetDelim.from - 4;
          } else {
            insertPos = doc.length;
          }
          view.dispatch({
            changes: [
              // Delete from original position
              {
                from: sourceStartDelim.from - 4,
                to: sourceEndDelim.to + 1,
                insert: ""
              },
              // Insert at new position (adjust if needed based on deletion)
              {
                from: insertPos > cardData.startPos ? insertPos - (sourceEndDelim.to - sourceStartDelim.from + 5) : insertPos,
                insert: fullCardContent + "\n"
              }
            ]
          });
          return true;
        },
        dragend: (e) => {
          const target = e.target;
          target.classList.remove("tps-card-dragging");
          return false;
        }
      }
    }
  );
  return [viewPlugin, createReadOnlyFilter()];
}

// src/reading-mode-processor.ts
var import_obsidian4 = require("obsidian");
var ReadingModeProcessor = class {
  constructor(app) {
    this.app = app;
  }
  async process(el, ctx) {
    var _a;
    const sourceFile = this.app.vault.getAbstractFileByPath(ctx.sourcePath);
    if (!(sourceFile instanceof import_obsidian4.TFile))
      return;
    const content = await this.app.vault.read(sourceFile);
    const lines = content.split("\n");
    let contentStartLine = 0;
    if (((_a = lines[0]) == null ? void 0 : _a.trim()) === "---") {
      const frontmatterEnd = lines.findIndex((line, idx) => idx > 0 && line.trim() === "---");
      if (frontmatterEnd !== -1) {
        contentStartLine = frontmatterEnd + 1;
      }
    }
    const delimiterLines = [];
    for (let i = contentStartLine; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        delimiterLines.push(i);
      }
    }
    const cards = [];
    if (delimiterLines.length >= 2) {
      for (let i = 0; i < delimiterLines.length - 1; i++) {
        const startLine = delimiterLines[i] + 1;
        const endLine = delimiterLines[i + 1] - 1;
        if (startLine <= endLine) {
          const cardContent = lines.slice(startLine, endLine + 1).join("\n");
          cards.push({ startLine, endLine, content: cardContent });
        }
      }
    } else {
      const contentLines = lines.slice(contentStartLine);
      const cardContent = contentLines.join("\n");
      if (cardContent.trim().length > 0 || delimiterLines.length === 0) {
        cards.push({
          startLine: contentStartLine,
          endLine: lines.length - 1,
          content: cardContent
        });
      }
    }
    el.empty();
    const container = el.createDiv({ cls: "tps-canvas-reading-container" });
    for (let i = 0; i < cards.length; i++) {
      const card = cards[i];
      const cardEl = container.createDiv({
        cls: card.content.trim() === "" ? "tps-canvas-card tps-canvas-card-empty" : "tps-canvas-card"
      });
      cardEl.setAttribute("draggable", "true");
      cardEl.setAttribute("data-card-index", i.toString());
      const contentEl = cardEl.createDiv({ cls: "tps-canvas-card-content" });
      await this.renderMarkdown(card.content, contentEl, ctx);
      const menuBtn = cardEl.createDiv({ cls: "tps-card-menu-button" });
      (0, import_obsidian4.setIcon)(menuBtn, "more-vertical");
      menuBtn.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.showCardMenu(e, card, sourceFile);
      });
      this.setupDragHandlers(cardEl, i, cards, sourceFile);
      const insertionZone = container.createDiv({ cls: "tps-card-insertion-zone" });
      insertionZone.setAttribute("data-insert-after", i.toString());
      this.setupInsertionZone(insertionZone, sourceFile);
    }
    const finalZone = container.createDiv({ cls: "tps-card-insertion-zone" });
    finalZone.setAttribute("data-insert-after", (cards.length - 1).toString());
    this.setupInsertionZone(finalZone, sourceFile);
  }
  async renderMarkdown(markdown, container, ctx) {
    await window.MarkdownRenderer.renderMarkdown(
      markdown,
      container,
      ctx.sourcePath,
      this.app.workspace.getActiveViewOfType(window.MarkdownView)
    );
  }
  setupDragHandlers(cardEl, cardIndex, cards, file) {
    cardEl.addEventListener("dragstart", (e) => {
      if (!(e instanceof DragEvent))
        return;
      if (!e.dataTransfer)
        return;
      e.dataTransfer.setData("application/tps-card-index", cardIndex.toString());
      e.dataTransfer.effectAllowed = "move";
      cardEl.classList.add("tps-card-dragging");
    });
    cardEl.addEventListener("dragover", (e) => {
      var _a;
      if (!(e instanceof DragEvent))
        return;
      if (!((_a = e.dataTransfer) == null ? void 0 : _a.types.includes("application/tps-card-index")))
        return;
      e.preventDefault();
      e.dataTransfer.dropEffect = "move";
      cardEl.classList.add("tps-card-drop-target");
    });
    cardEl.addEventListener("dragleave", () => {
      cardEl.classList.remove("tps-card-drop-target");
    });
    cardEl.addEventListener("drop", async (e) => {
      if (!(e instanceof DragEvent))
        return;
      if (!e.dataTransfer)
        return;
      e.preventDefault();
      cardEl.classList.remove("tps-card-drop-target");
      const sourceIndex = parseInt(e.dataTransfer.getData("application/tps-card-index"));
      const targetIndex = cardIndex;
      if (sourceIndex === targetIndex)
        return;
      await this.moveCard(file, sourceIndex, targetIndex);
    });
    cardEl.addEventListener("dragend", () => {
      cardEl.classList.remove("tps-card-dragging");
    });
  }
  setupInsertionZone(zone, file) {
    zone.addEventListener("click", async (e) => {
      e.preventDefault();
      const insertAfter = parseInt(zone.getAttribute("data-insert-after") || "0");
      await this.insertNewCard(file, insertAfter);
    });
    zone.addEventListener("contextmenu", async (e) => {
      e.preventDefault();
      new import_obsidian4.Notice("Right-click embed not yet implemented in Reading Mode");
    });
  }
  showCardMenu(event, card, file) {
    const menu = new import_obsidian4.Menu();
    menu.addItem(
      (item) => item.setTitle("Extract to note").setIcon("file-plus").onClick(async () => {
        await this.extractCard(file, card);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Delete card").setIcon("trash").onClick(async () => {
        await this.deleteCard(file, card);
      })
    );
    menu.showAtMouseEvent(event);
  }
  async moveCard(file, fromIndex, toIndex) {
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const cards = this.parseCardsFromLines(lines);
    if (fromIndex >= cards.length || toIndex >= cards.length)
      return;
    const sourceCard = cards[fromIndex];
    const cardLines = lines.slice(sourceCard.delimiterStart, sourceCard.delimiterEnd + 1);
    lines.splice(sourceCard.delimiterStart, sourceCard.delimiterEnd - sourceCard.delimiterStart + 1);
    const updatedCards = this.parseCardsFromLines(lines);
    const targetCard = updatedCards[toIndex > fromIndex ? toIndex - 1 : toIndex];
    if (!targetCard) {
      lines.push(...cardLines);
    } else {
      lines.splice(targetCard.delimiterStart, 0, ...cardLines);
    }
    await this.app.vault.modify(file, lines.join("\n"));
    new import_obsidian4.Notice("Card moved");
  }
  async insertNewCard(file, afterIndex) {
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const cards = this.parseCardsFromLines(lines);
    const insertPos = cards[afterIndex] ? cards[afterIndex].delimiterEnd + 1 : lines.length;
    lines.splice(insertPos, 0, "---", "", "---");
    await this.app.vault.modify(file, lines.join("\n"));
    new import_obsidian4.Notice("New card created");
  }
  async deleteCard(file, card) {
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const cards = this.parseCardsFromLines(lines);
    const cardToDelete = cards.find(
      (c) => c.startLine === card.startLine && c.endLine === card.endLine
    );
    if (!cardToDelete)
      return;
    lines.splice(
      cardToDelete.delimiterStart,
      cardToDelete.delimiterEnd - cardToDelete.delimiterStart + 1
    );
    await this.app.vault.modify(file, lines.join("\n"));
    new import_obsidian4.Notice("Card deleted");
  }
  async extractCard(file, card) {
    new import_obsidian4.Notice("Extract not yet implemented in Reading Mode");
  }
  parseCardsFromLines(lines) {
    var _a;
    let contentStartLine = 0;
    if (((_a = lines[0]) == null ? void 0 : _a.trim()) === "---") {
      const frontmatterEnd = lines.findIndex((line, idx) => idx > 0 && line.trim() === "---");
      if (frontmatterEnd !== -1) {
        contentStartLine = frontmatterEnd + 1;
      }
    }
    const delimiterLines = [];
    for (let i = contentStartLine; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        delimiterLines.push(i);
      }
    }
    const cards = [];
    for (let i = 0; i < delimiterLines.length - 1; i++) {
      cards.push({
        delimiterStart: delimiterLines[i],
        delimiterEnd: delimiterLines[i + 1],
        startLine: delimiterLines[i] + 1,
        endLine: delimiterLines[i + 1] - 1
      });
    }
    return cards;
  }
};

// src/card-initializer.ts
function initializeCardStructure(view) {
  var _a;
  const doc = view.state.doc;
  const text = doc.toString();
  const lines = text.split("\n");
  let contentStartIdx = 0;
  if (((_a = lines[0]) == null ? void 0 : _a.trim()) === "---") {
    const frontmatterEnd = lines.findIndex((line, idx) => idx > 0 && line.trim() === "---");
    if (frontmatterEnd !== -1) {
      contentStartIdx = frontmatterEnd + 1;
    }
  }
  const contentLines = lines.slice(contentStartIdx);
  const hasDelimiters = contentLines.some((line) => line.trim() === "---");
  if (hasDelimiters) {
    return false;
  }
  const hasContent = contentLines.some((line) => line.trim().length > 0);
  const frontmatterLines = lines.slice(0, contentStartIdx);
  const frontmatter = frontmatterLines.join("\n");
  let newContent;
  if (hasContent) {
    const existingContent = contentLines.join("\n").trim();
    newContent = `${frontmatter}
---
${existingContent}

---
`;
  } else {
    newContent = `${frontmatter}
---

---
`;
  }
  view.dispatch({
    changes: {
      from: 0,
      to: doc.length,
      insert: newContent
    }
  });
  return true;
}

// src/settings-tab.ts
var import_obsidian5 = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  dailyNotesOnly: true,
  showInsertionZones: "hover",
  defaultExtractFolder: ""
  // Empty = vault default
};
var TPSCanvasNotesSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "TPS Canvas Notes Settings" });
    new import_obsidian5.Setting(containerEl).setName("Enable Canvas Notes").setDesc("Master toggle for the canvas card interface").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
        this.plugin.updateExtension();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Daily Notes Only").setDesc("Only activate canvas mode for Daily Notes (recommended)").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.dailyNotesOnly).onChange(async (value) => {
        this.plugin.settings.dailyNotesOnly = value;
        await this.plugin.saveSettings();
        this.plugin.updateExtension();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Insertion Zone Visibility").setDesc("When to show the clickable zones between cards").addDropdown(
      (dropdown) => dropdown.addOption("always", "Always visible").addOption("hover", "Show on hover").addOption("drag-only", "Only when dragging").setValue(this.plugin.settings.showInsertionZones).onChange(async (value) => {
        this.plugin.settings.showInsertionZones = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Default Extract Folder").setDesc("Where to save extracted notes (leave blank for vault default)").addText(
      (text) => text.setPlaceholder("e.g., Notes/Extracted").setValue(this.plugin.settings.defaultExtractFolder).onChange(async (value) => {
        this.plugin.settings.defaultExtractFolder = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Usage Instructions" });
    containerEl.createEl("p", {
      text: "Add --- delimiters to create cards in your daily notes. Content between delimiters becomes a draggable card."
    });
    containerEl.createEl("p", {
      text: "Click between cards to create new empty cards. Right-click to embed an existing note."
    });
    containerEl.createEl("p", {
      text: "Hover over a card to see the menu button (\u22EE) for extract/delete options."
    });
  }
};

// src/main.ts
var TPSCanvasNotesPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.extensionArray = [];
  }
  async onload() {
    await this.loadSettings();
    this.readingModeProcessor = new ReadingModeProcessor(this.app);
    this.addSettingTab(new TPSCanvasNotesSettingTab(this.app, this));
    this.registerEditorExtension(this.extensionArray);
    this.registerMarkdownPostProcessor(async (el, ctx) => {
      if (!this.settings.enabled)
        return;
      if (this.settings.dailyNotesOnly) {
        const file = this.app.vault.getAbstractFileByPath(ctx.sourcePath);
        if (file instanceof import_obsidian6.TFile && !this.isDailyNote(file)) {
          return;
        }
      }
      await this.readingModeProcessor.process(el, ctx);
    });
    this.addCommand({
      id: "toggle-canvas-notes",
      name: "Toggle Canvas Notes mode",
      callback: () => {
        this.settings.enabled = !this.settings.enabled;
        this.saveSettings();
        this.updateExtension();
        new import_obsidian6.Notice(`Canvas Notes ${this.settings.enabled ? "Enabled" : "Disabled"}`);
      }
    });
    this.addCommand({
      id: "insert-card-delimiter",
      name: "Insert card delimiter (---)",
      editorCallback: (editor) => {
        const cursor = editor.getCursor();
        editor.replaceRange("---\n", cursor);
      }
    });
    this.updateExtension();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        if (!this.settings.enabled || !this.settings.dailyNotesOnly)
          return;
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
        if (!activeView)
          return;
        const file = activeView.file;
        if (!file || !this.isDailyNote(file))
          return;
        setTimeout(() => {
          const editor = activeView.editor;
          if (!editor)
            return;
          const cm6View = editor.cm;
          if (cm6View) {
            initializeCardStructure(cm6View);
          }
        }, 100);
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.updateExtension();
      })
    );
    console.log("TPS Canvas Notes Plugin Loaded");
  }
  onunload() {
    console.log("TPS Canvas Notes Plugin Unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateExtension() {
    this.extensionArray.length = 0;
    if (this.settings.enabled) {
      const shouldActivate = () => {
        if (!this.settings.dailyNotesOnly) {
          return true;
        }
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile) {
          return false;
        }
        if (!this.isDailyNote(activeFile)) {
          return false;
        }
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
        if (!activeView) {
          return false;
        }
        const mode = activeView.getMode();
        return mode === "preview";
      };
      const extensions = buildCanvasExtension(this.app, shouldActivate);
      this.extensionArray.push(...extensions);
    }
    this.app.workspace.updateOptions();
  }
  isDailyNote(file) {
    try {
      const { getAllDailyNotes } = require("obsidian-daily-notes-interface");
      const dailyNotes = getAllDailyNotes();
      return Object.values(dailyNotes).some((note) => note.path === file.path);
    } catch (e) {
      const dailyNotesFolder = this.app.vault.getConfig("dailyNotesFolder") || "";
      return file.path.startsWith(dailyNotesFolder);
    }
  }
};
